/*
 * generated by Xtext 2.12.0
 */
package algorithms.complexities.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class ComplexitiesWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public ComplexitiesWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
