/*
 * generated by Xtext 2.12.0
 */
package algorithms.complexities.ui.wizard;

import org.eclipse.xtext.ui.wizard.DefaultProjectInfo;

public class ComplexitiesProjectInfo extends DefaultProjectInfo {

}
