/**
 * generated by Xtext 2.12.0
 */
package algorithms.complexities.complexities;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Calculation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link algorithms.complexities.complexities.Calculation#getComplexity <em>Complexity</em>}</li>
 *   <li>{@link algorithms.complexities.complexities.Calculation#getTime1 <em>Time1</em>}</li>
 *   <li>{@link algorithms.complexities.complexities.Calculation#getTime1Unit <em>Time1 Unit</em>}</li>
 *   <li>{@link algorithms.complexities.complexities.Calculation#getSize1 <em>Size1</em>}</li>
 *   <li>{@link algorithms.complexities.complexities.Calculation#getTime2Unit <em>Time2 Unit</em>}</li>
 * </ul>
 *
 * @see algorithms.complexities.complexities.ComplexitiesPackage#getCalculation()
 * @model
 * @generated
 */
public interface Calculation extends EObject
{
  /**
   * Returns the value of the '<em><b>Complexity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Complexity</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Complexity</em>' attribute.
   * @see #setComplexity(String)
   * @see algorithms.complexities.complexities.ComplexitiesPackage#getCalculation_Complexity()
   * @model
   * @generated
   */
  String getComplexity();

  /**
   * Sets the value of the '{@link algorithms.complexities.complexities.Calculation#getComplexity <em>Complexity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Complexity</em>' attribute.
   * @see #getComplexity()
   * @generated
   */
  void setComplexity(String value);

  /**
   * Returns the value of the '<em><b>Time1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Time1</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time1</em>' attribute.
   * @see #setTime1(int)
   * @see algorithms.complexities.complexities.ComplexitiesPackage#getCalculation_Time1()
   * @model
   * @generated
   */
  int getTime1();

  /**
   * Sets the value of the '{@link algorithms.complexities.complexities.Calculation#getTime1 <em>Time1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time1</em>' attribute.
   * @see #getTime1()
   * @generated
   */
  void setTime1(int value);

  /**
   * Returns the value of the '<em><b>Time1 Unit</b></em>' attribute.
   * The literals are from the enumeration {@link algorithms.complexities.complexities.TimeUnits}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Time1 Unit</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time1 Unit</em>' attribute.
   * @see algorithms.complexities.complexities.TimeUnits
   * @see #setTime1Unit(TimeUnits)
   * @see algorithms.complexities.complexities.ComplexitiesPackage#getCalculation_Time1Unit()
   * @model
   * @generated
   */
  TimeUnits getTime1Unit();

  /**
   * Sets the value of the '{@link algorithms.complexities.complexities.Calculation#getTime1Unit <em>Time1 Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time1 Unit</em>' attribute.
   * @see algorithms.complexities.complexities.TimeUnits
   * @see #getTime1Unit()
   * @generated
   */
  void setTime1Unit(TimeUnits value);

  /**
   * Returns the value of the '<em><b>Size1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Size1</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size1</em>' attribute.
   * @see #setSize1(int)
   * @see algorithms.complexities.complexities.ComplexitiesPackage#getCalculation_Size1()
   * @model
   * @generated
   */
  int getSize1();

  /**
   * Sets the value of the '{@link algorithms.complexities.complexities.Calculation#getSize1 <em>Size1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size1</em>' attribute.
   * @see #getSize1()
   * @generated
   */
  void setSize1(int value);

  /**
   * Returns the value of the '<em><b>Time2 Unit</b></em>' attribute.
   * The literals are from the enumeration {@link algorithms.complexities.complexities.TimeUnits}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Time2 Unit</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time2 Unit</em>' attribute.
   * @see algorithms.complexities.complexities.TimeUnits
   * @see #setTime2Unit(TimeUnits)
   * @see algorithms.complexities.complexities.ComplexitiesPackage#getCalculation_Time2Unit()
   * @model
   * @generated
   */
  TimeUnits getTime2Unit();

  /**
   * Sets the value of the '{@link algorithms.complexities.complexities.Calculation#getTime2Unit <em>Time2 Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time2 Unit</em>' attribute.
   * @see algorithms.complexities.complexities.TimeUnits
   * @see #getTime2Unit()
   * @generated
   */
  void setTime2Unit(TimeUnits value);

} // Calculation
