/**
 * generated by Xtext 2.12.0
 */
package algorithms.complexities.complexities;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Execution Times</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link algorithms.complexities.complexities.ExecutionTimes#getSize2 <em>Size2</em>}</li>
 * </ul>
 *
 * @see algorithms.complexities.complexities.ComplexitiesPackage#getExecutionTimes()
 * @model
 * @generated
 */
public interface ExecutionTimes extends Calculation
{
  /**
   * Returns the value of the '<em><b>Size2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Size2</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size2</em>' attribute.
   * @see #setSize2(int)
   * @see algorithms.complexities.complexities.ComplexitiesPackage#getExecutionTimes_Size2()
   * @model
   * @generated
   */
  int getSize2();

  /**
   * Sets the value of the '{@link algorithms.complexities.complexities.ExecutionTimes#getSize2 <em>Size2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size2</em>' attribute.
   * @see #getSize2()
   * @generated
   */
  void setSize2(int value);

} // ExecutionTimes
