/**
 * generated by Xtext 2.12.0
 */
package algorithms.complexities.complexities;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link algorithms.complexities.complexities.Model#getCalculations <em>Calculations</em>}</li>
 * </ul>
 *
 * @see algorithms.complexities.complexities.ComplexitiesPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Calculations</b></em>' containment reference list.
   * The list contents are of type {@link algorithms.complexities.complexities.Calculation}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Calculations</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Calculations</em>' containment reference list.
   * @see algorithms.complexities.complexities.ComplexitiesPackage#getModel_Calculations()
   * @model containment="true"
   * @generated
   */
  EList<Calculation> getCalculations();

} // Model
