/**
 * generated by Xtext 2.12.0
 */
package algorithms.complexities.complexities;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sizes</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link algorithms.complexities.complexities.Sizes#getTime2 <em>Time2</em>}</li>
 * </ul>
 *
 * @see algorithms.complexities.complexities.ComplexitiesPackage#getSizes()
 * @model
 * @generated
 */
public interface Sizes extends Calculation
{
  /**
   * Returns the value of the '<em><b>Time2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Time2</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time2</em>' attribute.
   * @see #setTime2(int)
   * @see algorithms.complexities.complexities.ComplexitiesPackage#getSizes_Time2()
   * @model
   * @generated
   */
  int getTime2();

  /**
   * Sets the value of the '{@link algorithms.complexities.complexities.Sizes#getTime2 <em>Time2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time2</em>' attribute.
   * @see #getTime2()
   * @generated
   */
  void setTime2(int value);

} // Sizes
