/*
 * generated by Xtext 2.12.0
 */
package algorithms.complexities.parser.antlr;

import algorithms.complexities.parser.antlr.internal.InternalComplexitiesParser;
import algorithms.complexities.services.ComplexitiesGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ComplexitiesParser extends AbstractAntlrParser {

	@Inject
	private ComplexitiesGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalComplexitiesParser createParser(XtextTokenStream stream) {
		return new InternalComplexitiesParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ComplexitiesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ComplexitiesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
