/*
 * generated by Xtext 2.12.0
 */
package algorithms.complexities.ui;

import algorithms.complexities.ui.internal.ComplexitiesActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ComplexitiesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ComplexitiesActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ComplexitiesActivator.getInstance().getInjector(ComplexitiesActivator.ALGORITHMS_COMPLEXITIES_COMPLEXITIES);
	}
	
}
