/**
 * generated by Xtext 2.12.0
 */
package algorithms.complexities.ui.contentassist;

import algorithms.complexities.ui.contentassist.AbstractComplexitiesProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ComplexitiesProposalProvider extends AbstractComplexitiesProposalProvider {
}
