/**
 * generated by Xtext 2.12.0
 */
package algorithms.complexities.ui;

import algorithms.complexities.ui.AbstractComplexitiesUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ComplexitiesUiModule extends AbstractComplexitiesUiModule {
  public ComplexitiesUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
