/*
 * generated by Xtext 2.12.0
 */
package algorithms.complexities.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractComplexitiesValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(algorithms.complexities.complexities.ComplexitiesPackage.eINSTANCE);
		return result;
	}
	
}
