/*
 * generated by Xtext 2.12.0
 */
package algorithms.complexities.ui.wizard;

import org.eclipse.xtext.ui.wizard.XtextNewProjectWizard;

import org.eclipse.xtext.ui.wizard.IExtendedProjectInfo;
import org.eclipse.xtext.ui.wizard.IProjectCreator;
import com.google.inject.Inject;

public class ComplexitiesNewProjectWizard extends XtextNewProjectWizard {

	private ComplexitiesWizardNewProjectCreationPage mainPage;

	@Inject
	public ComplexitiesNewProjectWizard(IProjectCreator projectCreator) {
		super(projectCreator);
		setWindowTitle("New Complexities Project");
	}

	protected ComplexitiesWizardNewProjectCreationPage getMainPage() {
		return mainPage;
	}

	/**
	 * Use this method to add pages to the wizard.
	 * The one-time generated version of this class will add a default new project page to the wizard.
	 */
	@Override
	public void addPages() {
		mainPage = createMainPage("basicNewProjectPage");
		mainPage.setTitle("Complexities Project");
		mainPage.setDescription("Create a new Complexities project.");
		addPage(mainPage);
	}

	protected ComplexitiesWizardNewProjectCreationPage createMainPage(String pageName) {
		return new ComplexitiesWizardNewProjectCreationPage(pageName);
	}

	/**
	 * Use this method to read the project settings from the wizard pages and feed them into the project info class.
	 */
	@Override
	protected IExtendedProjectInfo getProjectInfo() {
		ComplexitiesProjectInfo projectInfo = new ComplexitiesProjectInfo();
		projectInfo.setProjectName(mainPage.getProjectName());
		if (!mainPage.useDefaults()) {
			projectInfo.setLocationPath(mainPage.getLocationPath());
		}
		return projectInfo;
	}

}
