/**
 * generated by Xtext 2.12.0
 */
package algorithms.complexities.ide;

import algorithms.complexities.ide.AbstractComplexitiesIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ComplexitiesIdeModule extends AbstractComplexitiesIdeModule {
}
