/*
 * generated by Xtext 2.12.0
 */
package algorithms.complexities.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractComplexitiesScopeProvider extends DelegatingScopeProvider {
}
