/**
 * generated by Xtext 2.12.0
 */
package algorithms.complexities;

import algorithms.complexities.AbstractComplexitiesRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ComplexitiesRuntimeModule extends AbstractComplexitiesRuntimeModule {
}
