/**
 * generated by Xtext 2.12.0
 */
package algorithms.complexities.complexities.impl;

import algorithms.complexities.complexities.ComplexitiesPackage;
import algorithms.complexities.complexities.Sizes;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sizes</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link algorithms.complexities.complexities.impl.SizesImpl#getTime2 <em>Time2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SizesImpl extends CalculationImpl implements Sizes
{
  /**
   * The default value of the '{@link #getTime2() <em>Time2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTime2()
   * @generated
   * @ordered
   */
  protected static final int TIME2_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getTime2() <em>Time2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTime2()
   * @generated
   * @ordered
   */
  protected int time2 = TIME2_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SizesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ComplexitiesPackage.Literals.SIZES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getTime2()
  {
    return time2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTime2(int newTime2)
  {
    int oldTime2 = time2;
    time2 = newTime2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComplexitiesPackage.SIZES__TIME2, oldTime2, time2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ComplexitiesPackage.SIZES__TIME2:
        return getTime2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ComplexitiesPackage.SIZES__TIME2:
        setTime2((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ComplexitiesPackage.SIZES__TIME2:
        setTime2(TIME2_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ComplexitiesPackage.SIZES__TIME2:
        return time2 != TIME2_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (time2: ");
    result.append(time2);
    result.append(')');
    return result.toString();
  }

} //SizesImpl
