/**
 * generated by Xtext 2.12.0
 */
package algorithms.complexities.validation;

import algorithms.complexities.validation.AbstractComplexitiesValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ComplexitiesValidator extends AbstractComplexitiesValidator {
}
